"""empty message

Revision ID: 286223cf8b6d
Revises: dd3c017cc226
Create Date: 2025-12-03 18:21:31.062646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286223cf8b6d'
down_revision = 'dd3c017cc226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
